version: "3.8"

services:
  roma:
    image: binrc/roma:latest
    container_name: roma
    restart: unless-stopped
    ports:
      - "2200:2200"
      - "6999:6999"
      - "80:80"
    volumes:
      - roma-data:/app/data
      - ./config.toml:/app/configs/config.toml:ro
    environment:
      - ROMA_BASE_ROOT=/app
      - APP_ENV=production
    # healthcheck:
    #   test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6999/health"]
    #   interval: 30s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 10s

volumes:
  roma-data:
    driver: local
