title = 'Roma Configs File'

[api]
gin_mode = 'release'
host = '0.0.0.0'
port = '6999'

[common]
language = 'zh'
port = '2200'
prompt = 'roma'

[database]
cdb_url = '/usr/local/roma/c.db'
rdb_passwd = ''
rdb_url = ''

[log]
level = 'debug'

[apikey]
prefix = 'apikey.'
key = 'AAAA2EAAHBZY26A25wOraC1c2E2BxkKFrNmWoLMOXwWVnwFv5s7Q8w'

[user_1st]
email = 'super@test.x'
name = '超级管理员'
nickname = 'Super'
password = 'super001.'
public_key = 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHBGKPvWEf8rUzt90micFv5sF/rIjjDVgkP3UwFwpW+//jEkNObsG79IeEltckTZG+SCC4K2byXb5+XaJ8gJRB+q/1u7xNPgiX3Qz6o2keZz3cElLmCwSUE61KouSfzq3aV67dd1RFSt9tTNqgwfZczvAwv7K2dkwVDvayEdat2bnZmIJZz8EZTXH4lckV6H9m82SPENnEVA/s31oHLmkvEG7kDuKjnF9VVojIwEUR6CCMzYqWRxcaIgXe/+fOh5ScBB6ByUbHItJ4Iovl4YmDXO0QYYv/QajaWWyqueIIhbHbfb5yh8FPvTVr4fv77wZKlpyokdkcZcIaL4vdkHoNBzctUShxu8i+2LPcGoeHF7xFtQZ6jE9jIiLhvwZlUZaFt4CpaH9Z5hU+/5utoXKFTomLBHh71Ku3ofG5l2bPWK/+TIsoF2fLKdQqith0vjZxsZisQre7sJFpDKaXiTZXeOxkx6PNwxe5tGNMKgbZ82ImKAWYaLeNzeeSGEMeld5wLXHUyOhL3+bQhA+k2E7MPOpZF+HN5x7DpYVizwASzMQNo2To7CRDiNQhQwHZm8g4+5wcXRdTpPvInNBU+L6egWLqgvZyv9h6xxMtP8TGQhX1yS0H9v3GUjbm8eD5lLIMe0aUTPtyyytCqM8gMWSxY9mGRtIjlQiQ59IB6yYELQ== control@bitrec.ai'
username = 'super'
roles = "super,system,ops,ordinary,trial"

[control_passport]
service_user = 'root'
password = ''
resource_type = 'linux'
passport_pub = 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHBGKPvWEf8rUzt90micFv5sF/rIjjDVgkP3UwFwpW+//jEkNObsG79IeEltckTZG+SCC4K2byXb5+XaJ8gJRB+q/1u7xNPgiX3Qz6o2keZz3cElLmCwSUE61KouSfzq3aV67dd1RFSt9tTNqgwfZczvAwv7K2dkwVDvayEdat2bnZmIJZz8EZTXH4lckV6H9m82SPENnEVA/s31oHLmkvEG7kDuKjnF9VVojIwEUR6CCMzYqWRxcaIgXe/+fOh5ScBB6ByUbHItJ4Iovl4YmDXO0QYYv/QajaWWyqueIIhbHbfb5yh8FPvTVr4fv77wZKlpyokdkcZcIaL4vdkHoNBzctUShxu8i+2LPcGoeHF7xFtQZ6jE9jIiLhvwZlUZaFt4CpaH9Z5hU+/5utoXKFTomLBHh71Ku3ofG5l2bPWK/+TIsoF2fLKdQqith0vjZxsZisQre7sJFpDKaXiTZXeOxkx6PNwxe5tGNMKgbZ82ImKAWYaLeNzeeSGEMeld5wLXHUyOhL3+bQhA+k2E7MPOpZF+HN5x7DpYVizwASzMQNo2To7CRDiNQhQwHZm8g4+5wcXRdTpPvInNBU+L6egWLqgvZyv9h6xxMtP8TGQhX1yS0H9v3GUjbm8eD5lLIMe0aUTPtyyytCqM8gMWSxY9mGRtIjlQiQ59IB6yYELQ== control@bitrec.ai'
passport = '''-----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAACFwAAAAdzc2gtcn
NhAAAAAwEAAQAAAgEAxwRij71hH/K1M7fdJonBb+bBf6yI4w1YJD91MBcKVvv/4xJDTm7B
u/SHhJbXJE2RvkgguCtm8l2+fl2ifICUQfqv9bu8TT4Il90M+qNpHmc93BJS5gsElBOtSq
Lkn86t2leu3XdURUrfbUzaoMH2XM7wML+ytnZMFQ72shHWrdm52ZiCWc/BGU1x+JXJFeh/
ZvNkjxDZxFQP7N9aBy5pLxBu5A7io5xfVVaIyMBFEeggjM2KlkcXGiIF3v/nzoeUnAQegc
lGxyLSeCKL5eGJg1ztEGGL/0Go2llsqrniCIWx232+cofBT701a+H7++8GSpacqJHZHGXC
Gi+L3ZB6DQc3LVEocbvIvtiz3BqHhxe8RbUGeoxPYyIi4b8GZVGWhbeAqWh/WeYVPv+bra
FyhU6JiwR4e9Srt6HxuZdmz1iv/kyLKBdnyynUKorYdL42cbGYrEK3u7CRaQyml4k2V3js
ZMejzcMXubRjTCoG2fNiJigFmGi3jc3nkhhDHpXecC1x1MjoS9/m0IQPpNhOzDzqWRfhze
cew6WFYs8AEszEDaNk6OwkQ4jUIUMB2ZvIOPucHF0XU6T7yJzQVPi+noFi6oL2cr/YescT
LT/ExkIV9cktB/b9xlI25vHg+ZSyDHtGlEz7cssrQqjPIDFksWPZhkbSI5UIkOfSAesmBC
0AAAdIRtPc5UbT3OUAAAAHc3NoLXJzYQAAAgEAxwRij71hH/K1M7fdJonBb+bBf6yI4w1Y
JD91MBcKVvv/4xJDTm7Bu/SHhJbXJE2RvkgguCtm8l2+fl2ifICUQfqv9bu8TT4Il90M+q
NpHmc93BJS5gsElBOtSqLkn86t2leu3XdURUrfbUzaoMH2XM7wML+ytnZMFQ72shHWrdm5
2ZiCWc/BGU1x+JXJFeh/ZvNkjxDZxFQP7N9aBy5pLxBu5A7io5xfVVaIyMBFEeggjM2Klk
cXGiIF3v/nzoeUnAQegclGxyLSeCKL5eGJg1ztEGGL/0Go2llsqrniCIWx232+cofBT701
a+H7++8GSpacqJHZHGXCGi+L3ZB6DQc3LVEocbvIvtiz3BqHhxe8RbUGeoxPYyIi4b8GZV
GWhbeAqWh/WeYVPv+braFyhU6JiwR4e9Srt6HxuZdmz1iv/kyLKBdnyynUKorYdL42cbGY
rEK3u7CRaQyml4k2V3jsZMejzcMXubRjTCoG2fNiJigFmGi3jc3nkhhDHpXecC1x1MjoS9
/m0IQPpNhOzDzqWRfhzecew6WFYs8AEszEDaNk6OwkQ4jUIUMB2ZvIOPucHF0XU6T7yJzQ
VPi+noFi6oL2cr/YescTLT/ExkIV9cktB/b9xlI25vHg+ZSyDHtGlEz7cssrQqjPIDFksW
PZhkbSI5UIkOfSAesmBC0AAAADAQABAAACAGMiLwpUlj24w0QI0TMyKVXZRweW5PTcn8wm
g/Q5deAQVM1COp6mEwDR9HM6Q96EeRWkjg/PJs+RnKMLdzW3QqJ/AglQw6JiRRuIc7+hiG
opmSm3Qu3uDRDJoGduLp3f8L+zL5qHp0WA3zxtrPWoyFRAjGpsAtRaptlSg9X9hsdAjg/y
pPOhxhkZd60Qx4KPNm8MzElrZl4iVXBzbT/ogWJ9OA+HzqMa8G3s1ePRylX6H8SjWeYzcT
GGQxBqvoglBwSUFLInlYb6NIa9BpyytLHnpvqi7H5wsXBaXQPJ5erC1e50e1pHfyZ+JE8h
2UgML0EWNuDNDa3UjlRG3M+3+OMFfE0acIq1jmbXVKmeTVvgXKPhCTRzMCXjmNaTCCNbcW
BFhe0kjuncTjmEmq77SoBoTCJbQYz8iD9gbDjJv/+5lBl4LxnH93DPmpSfgdzImxfS7G/6
JccgVqv31PLu2jAd2f26O/AyNfj059zmdv1s2pHUJ2PYmKnRzeeJzoKVUqwLlqr9cEXkD5
EFs1g1HaIhw1Q5QkCco3em9YpoDnA06qM0HuFB3NKMIiC7yc63ONMcNlIxj4JL23BWTfRp
5afys0iv4pId/ZZPMWIpsv4o0ZKgS9qSR16u8hzJ9iS2t7Wf20GWdYOwr0ifHKj9Ij3EaO
cywSKNTZVuNKQm9nYhAAABABAM1zu5aKb7mfm6PsedZ557iof3O5WOxcB2K9ui9g4Mqsmg
qLEkuGc5WmZauI/FKortNRIkXUDQYmmXnT+U6Hli0nOcC87SAdslXjXf+QPMsOYzWrLbUs
5ksnIsN/1HKh1aslYhDBsveQilhF50ti5tyN2A4SNAx//qCezU7PT+MsNifVw2uE+BSSLA
8laUA2pKqMsMIANyUcTDhTpDQ1+qphwdV2m+bKZ/Blh7ifDq279zA9mjlntQsMbkjLIBUZ
y6eg+VzNOPr00ntimPM0EnT4EL02s8vt78IJK2CbLJV+rvbqOiUi7p6y+4B2RP/XRcM0Wq
OK0wFbUpG9PQZtMAAAEBAOi9gLlTo4UC5/nVFPtBFxrANu8jlGTZPBlncoQbR4wWpSDi66
6RhyJW/7iGb0vSS2hi4hDtkDur5NLmefxnwZ+14KJaLBSDOCLZFdPCQyK8lhUD9gmupRcX
zFS5aES8n/iJwLz/poOXRYHlvwqoZfxfTPAeyoA++ruBbs23v8I8hiLuySxjdk//3iy5zN
G74kgRmtMPT8hOZ2R7AY7XpFxtpQEYNWpOP3igQMYXeYO4EehktBzf2ZQkmYsCR7Q8AgQW
XQmWywaDdb3t6twIsbyTeN3sihjk+cvwqrOgfEkcDZE4+STLEN+Dg2PM2aXsS4H1B3KwQs
MS2Xrn6HI9kikAAAEBANroGYcHXoE7KtITed0a5cq+v2A9DdDJqyIub2VWdCNUk4zJ5tR1
NATCjcTZsfDEVzS3EmobCZmp/oOzpwJq3F5lbK+PAG0AF+qXBBrzL2JnQuHIsF49VEB8gO
Ir8gwLP2jn3ObUaMInqor07DgYbuZ083+1XmdZelu3JHI7aTXx4CR6kk++iFkJTzIHQrIo
HNTxKcLwu2/0LBXmihQyf5YbA1Fs0Z1IOv8UEjDYMZ1XJKDKlt9A5WdAwB+005diG5Cyuu
KsU2UsvbsQ2A9kuNvN8oqKmVg8SLL3lzOCTS+iSgsdnacoL78K7fcW1hnUvNAgFN7/p1HU
Ud2+YL4vymUAAAARMzAzMTc5MTIzMkBxcS5jb20BAg==
-----END OPENSSH PRIVATE KEY-----
'''
description = "default control's passport , and ops use this passport"

[banner]
show = true
banner = '''
       ______
      /\     \
     />.\_____\
   __\  /  ___/__        _ROMA__
  /\  \/__/\     \  ____/
 /O \____/*?\_____\
 \  /    \  /     /                 [safe]
  \/_____/\/_____/
'''


#多角色设计
[[roles]]
name = "super"
desc = "all permissions [operation:user.(add|delete|update|get|list)]"

[[roles]]
name = "system"
desc = "system administrator [operation:resource.(add|delete|update|get|list)]"

[[roles]]
name = "ops"
desc = "system operations personnel [operation:resource.(get|list|use)]"

[[roles]]
name = "ordinary"
desc = "system ordinary [operation:resource-(*peripheral).(get|list)]"

[[roles]]
name = "trial"
desc = "system trial [operation:resource-(*trial).(get|list|use)]"
